config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :users
  resources :sessions
  root to: 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
require 'csv'
require 'socket'
class Product < ApplicationRecord

  def self.get_product_list(product_id)
    if product_id.present?
      get_product_detail = Product.where("id=?",product_id)
    else
      get_product_detail = Product.all()
    end

  end

  def self.to_csv(products,base_url)
    column_names = ["Name","Model","Brand","Year","RAM","Exteranl Storage","Link"]
    CSV.generate do |csv|
      csv << column_names
      arr = {}
      products.each do |data_csv|
        arr['name'] = data_csv['name']
        arr['model'] = data_csv['model']
        arr['brand'] = data_csv['brand']
        arr['year'] = data_csv['year']
        arr['ram'] = data_csv['ram']
        arr['external_sorage'] = data_csv['external_storage']
        arr['Link'] = "#{base_url}/products/id/#{data_csv['id']}"
        csv << arr.values
      end
    end

  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
    protect_from_forgery with: :exception

    private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
  
    helper_method :current_use
end

app/controllers/products_controller.rb
require 'csv'
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    page = params[:page] || 1
    per_page = params[:per_page] || 25
    @products_list = Product.all
    if params['name'].present? ||  params['brand'].present? || params['year'].present? || params['ram'].present? ||  params['external_storage'].present?
      name = params['name']
      brand = params['brand']
      model = params['model']
      year = params['year']
      ram = params['ram']
      external_storage = params['external_storage']
      where_clause = name.present? ? "name = '#{name}' and " : ''
      where_clause = where_clause+(brand.present? ? " brand='#{brand}' and " : '')
      where_clause = where_clause+(model.present? ? " model='#{model}' and " : '')
      where_clause =  where_clause+(year.present? ?  " year='#{year}' and " : '')
      where_clause =  where_clause+(ram.present? ? " ram='#{ram}' and " : '')
      where_clause =  where_clause+(external_storage.present? ? " external_storage='#{external_storage}'  " : '')
      check_clause = where_clause.split()

      if check_clause.last == "and"
        check_clause.pop
        where_clause = check_clause.join(" ")
      end
      @products = Product.where(where_clause).paginate(:page => page,:per_page =>per_page)
    else
      @products = @products_list.paginate(:page => page,:per_page =>per_page)
    end

    if params['products_download']
      respond_to do |format|
        format.html
        format.csv { send_data Product.to_csv(@products,request.base_url) }
      end
    end


  end



  # GET /products/1
  # GET /products/1.json
  def show
    product_id = params['id']
    @get_product = Product.get_product_list(product_id)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.fetch(:product, {})
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_path, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid."
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/test.rb
Complete the below given method which takes an array and prints the majority element
(if it exists), otherwise prints “No Majority Element”. A majority element in an array
A of size n is an element that appears more than n/2 times (and hence there is at most one such element).
    Test Cases:  I/P : [3, 3, 4, 2, 4, 4, 2, 4, 4] O/P : 4  I/P : [3, 3, 4, 2, 4, 4, 2, 4] O/P :
 end
    No Majority Element   def get_majority_element arr  # your code goes here end
    end

def cal_arr(arr=[3,3,4,2,4,4,2,4,4,3,3,3])
  size_of_arr = arr.count #n=9
  idx= size_od_arr/2 #4 3, , 2
  count = 1
  res = {}
  arr.each_with_index do |data,idx|
    res[data] = count+1
  end






  if (arr.include?idx)

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(permitted_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def get_name
    brand = @products_list.map{|e| {id:e.id,name:e.name}}
  end


  def get_brand
    brand = @products_list.map{|e| {id:e.id,brand:e.brand}}
  end

  def get_model
    get_model = @products_list.map{|e| {id:e.id,model:e.model}}
  end

  def get_ram
    ram_external_storage = @products_list.map{|e| {id:e.id,ram:e.ram}}
  end

  def get_external_storage
    ram_external_storage = @products_list.map{|e| {id:e.id,external_storage:e.external_storage}}
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProductProject</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<body>
<%  %>
<% if @current_user %>
    Logged in as <%= current_user.email %>

<% else %>
    <%= link_to "Sign Up", new_user_path %> or
    <%= link_to "Log In", new_session_path %>
    <%= link_to "Log Out", session_path("current"), method: "delete" %> |
    <%= link_to "Refresh", products_path %> |


<% end %>
<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
<% end %>

<%= yield %>

</body>
</body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">

  <div class="row">
    <div class="col-sm-2">
      <div class="dropdown">
        <form method="get">
          <label>Name</label>
          <select  name="name" class="form-control" >
            <option value="">Select Name</option>
            <% get_name.each do |name| %>
                <option value="<%=name[:name] %>"><%=name[:name] %></option>
            <% end %>
          </select>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="dropdown">
        <label>Brand</label>
        <select  name="brand" class="form-control" >
          <option value="">Select Brand</option>
          <% get_brand.each do |brand| %>
              <option value="<%=brand[:brand] %>"><%=brand[:brand] %></option>
          <% end %>
        </select>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="dropdown">
        <label>Model</label>
        <select  name="model"  class="form-control" >
          <option value="">Select Model</option>
          <% get_model.each do |model| %>
              <option value="<%= model[:model] %>"><%= model[:model] %></option>
          <% end %>
        </select>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="dropdown">
        <label>RAM</label>
        <select  name="ram"  class="form-control" >
          <option value="">Select RAM</option>
          <% get_ram.each do |ram| %>
              <option value="<%= ram[:ram] %>"><%= ram[:ram] %></option>
          <% end %>
        </select>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="dropdown">
        <label>External Storage</label>
        <select  name="external_storage"  class="form-control" >
          <option value="">Select External Storage</option>
          <% get_external_storage.each do |es| %>
              <option <%= %> value="<%= es[:external_storage] %>"><%= es[:external_storage] %></option>
          <% end %>
        </select>
      </div>
    </div>
    <button type="submit" class="btn btn-default">Search</button>
    <%= link_to "Excel", products_path(products_download:1,name:params['name'],brand:params['brand'],year:params['year'],ram:params['ram'],external_storage:params['external_storage'],format: "csv") %>

    </form>
  </div>

  <table class="table table-striped">
    <% if @products.present? %>
        <thead>
        <tr>
          <th>Sno</th>
          <th>Product Name</th>
          <th>Model</th>
          <th>Brand</th>
          <th>Year</th>
          <th>Ram External Storage</th>
          <th>View</th>
        </tr>
        </thead>
        <tbody>
        <% @products.each_with_index do |product,idx| %>
            <tr>
              <td><%= product.id%></td>
              <td><%= product.name%></td>
              <td><%= product.model%></td>
              <td><%= product.brand%></td>
              <td><%= product.year%></td>
              <td><%= product.ram%></td>
              <td><a href="/products/<%= product.id %>">View product</a></td>
            </tr>
        <% end %>
        </tbody>
    <% end %>
  </table>
</div>
<%= will_paginate @products%>

</body>
</html>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Product List</h2>
  <table class="table table-striped">
    <% if @get_product.present? %>
        <thead>
        <tr>
          <th>Product Name</th>
          <th>Model</th>
          <th>Brand</th>
          <th>Year</th>
          <th>Ram </th>
          <th>External Storage </th>
        </tr>
        </thead>
        <tbody>
        <% @get_product.each_with_index do |product,idx| %>
            <tr>
              <td><%= product.name%></td>
              <td><%= product.model%></td>
              <td><%= product.brand%></td>
              <td><%= product.year%></td>
              <td><%= product.ram%></td>
              <td><%= product.external_storage%></td>
            </tr>
        <% end %>
        </tbody>
    <% end %>
  </table>
</div>

</body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>